### PR TITLE
Added Docstrings

### PR DESCRIPTION
**Pull request by afro-coder**
I'm still learning, so in case this is incorrect please feel free to correct me and I'll make the changes.

### CODE REVIEW

**Comment by afro-coder** [comment]
Any idea why its failing if I add a tab and indentation it says space around docstring isn't allowed...

**Comment by ZigRazor** [comment]
Checkout this [Link](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces) probably you mixed tabs and spaces.
Use space to indent.

**Review by ZigRazor — CHANGES_REQUESTED** [review]
Please correct the CI Alerts

**Review by ZigRazor — APPROVED** [review]

**Comment by ZigRazor** [comment]
Good job @afro-coder! thank you so much!
If you want to add also docstring for function and attributes you are welcome!

**Pull request merged**
